name: Tests

# This workflow is triggered on pull requets to main branch (branches mentioned below)
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, WEBRTC-* ]
  
jobs:
  test:
    name: Unit Tests
    runs-on: macOS-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 12']
        xcode: ['/Applications/Xcode_12.5.1.app/Contents/Developer']
    
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v1
        
      #- name: Bundle install
      #  run: bundle install
        
      #- name: Pod install
      #  run: pod install
      
      - name: On-demand Credentials
        id: ondemand_creds
        run: |
          creds = `curl -X POST \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer KEY017AEC14FD7AD6CD8FCBF2F23D80DA59_8PNJjealo3EDelUwLl7pfH" \
          --data '{
            "connection_id": "1690412195747202634"
          }' \
          --url 'https://api.telnyx.com/v2/telephony_credentials'`
          echo "::set-output name=response::$creds"
          echo "Creds: ${{ creds }}"
          
      - name: Token
        id: generate_token
        run: |
          echo 'Generating token'
          token = `curl -X POST \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer KEY017AEC14FD7AD6CD8FCBF2F23D80DA59_8PNJjealo3EDelUwLl7pfH" \
          --data '{}' \
          --url 'https://api.telnyx.com/v2/telephony_credentials/${{ fromJson(steps.ondemand_creds.outputs.response).data.id }}/token'`
          echo "::set-output name=response::$token"
          echo 'Token response: ${{ $token }}'
        
      - name: Test
        run: |
          xcodebuild \
          -project TheDogSDK.xcodeproj \
          -scheme TheDogSDK \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.1' \
          test
    
